Repository MetaMask/contract-metadata, pull requests merged in 2020-11, with the labels that each got.

#545 DKA update
  contract-map.json
  images/DKA.svg
Labels: pending icon

#566 Add OctoFi
  contract-map.json
  images/octo.svg
Labels: invalid, pending tests

#565 Add REVV
  contract-map.json
  images/revv.svg
Labels: pending community activity

#605 Add USDN stablecoin
  contract-map.json
  images/usdn.svg
Labels: pending community activity
