Repository MetaMask/contract-metadata, pull requests merged in 2020-10, with the labels that each got.

#288 add RAE Token
  contract-map.json
  images/rae.svg
Labels: pending community activity, pending reputation

#310 Add C10 token
  contract-map.json
  images/c10.svg
Labels: pending reputation

#586 Add SNTVT
  contract-map.json
  images/sentivate.svg
Labels: pending-icon

#598 Add ANTv2
  contract-map.json
  images/antv1.svg
  images/antv2.svg
Labels: pending tests
