Repository MetaMask/contract-metadata, pull requests merged in 2021-09, with the labels that each got.

#698 add cryptokek coin and logo
  contract-map.json
  images/cryptokek.svg
Labels: pending community activity

#712 Add NWC token
  contract-map.json
  images/NWC.svg
Labels: pending community activity

#938 Add Million Token (MM)
  contract-map.json
  images/million.svg
Labels: bsc

#939 add spwn token
  contract-map.json
  images/spwn.svg
Labels: pending icon
